#! /bin/bash
clear
sudo apt-get update 
echo "Finish to get the packages"
echo ""
sudo apt-get upgrade 
echo "Finish to update your system"
echo ""
echo "============================================================================"
echo ""
echo "Is updated"
